spring:
  application:
    name: MailSender
  task:
    scheduling:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nebinmohammed.sa.007@gmail.com
    password: knyc iqac tngk rquu    
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/nebin_v3?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: AMD99#gch
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

email:
  from-email: nebinmohammed.sa.007@gmail.com
  from-name: Mohammed Nebin - Based in UAE
  subject: Immediate Joiner - Full Stack/Backend Developer (Java/Spring Boot/Angular) - 5+ Years Exp - Mohammed Nebin B S
  attachments-folder: /home/mohammed-nebin/Mail Attach
  template-file: /home/mohammed-nebin/Documents/Resumes/AutomateMailTemplate.txt
  
server:
  port: 8083
